name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push ctxsh/java
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push jdk8
        uses: docker/build-push-action@v2.5.0
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            URL=https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u282-b08/OpenJDK8U-jdk_x64_linux_hotspot_8u282b08.tar.gz
          tags: |
            ctxsh/java:jdk8

      - name: Build and push jre8
        uses: docker/build-push-action@v2.5.0
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            URL=https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u282-b08/OpenJDK8U-jre_x64_linux_hotspot_8u282b08.tar.gz
          tags:
            ctxsh/java:jre8

      - name: Build and push jdk11
        uses: docker/build-push-action@v2.5.0
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            URL=https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.10%2B9/OpenJDK11U-jdk_x64_linux_hotspot_11.0.10_9.tar.gz
          tags: |
            ctxsh/java:jdk11

      - name: Build and push jre11
        uses: docker/build-push-action@v2.5.0
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            URL=https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.10%2B9/OpenJDK11U-jre_x64_linux_hotspot_11.0.10_9.tar.gz
          tags:
            ctxsh/java:jre11

      - name: Build and push jdk14
        uses: docker/build-push-action@v2.5.0
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            URL=https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14.0.2%2B12/OpenJDK14U-jdk_x64_linux_hotspot_14.0.2_12.tar.gz
          tags: |
            ctxsh/java:jdk14

      - name: Build and push jre14
        uses: docker/build-push-action@v2.5.0
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            URL=https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14.0.2%2B12/OpenJDK14U-jre_x64_linux_hotspot_14.0.2_12.tar.gz
          tags:
            ctxsh/java:jre14
